#!/bin/bash

# rewee is an alias as it needs to modify current shell env
rewee ()
{
	[ ! -f ".mise.toml" ] && return 0
	local cmd="$(cat /tmp/rewee-cmd 2>/dev/null)"
	rm -rf /tmp/rewee-cmd
	[ -n "$cmd" ] && cmd="$cmd; cd; cd -" || cmd="cd; cd -"
	eval "$cmd"
	return 0
}
